### ISSUE TITLE
Date de logare in interiorul codului...

### ISSUE THREAD

**Issue by sica07** [BiancaBM/medicalApp-PHP#1]
https://github.com/BiancaBM/medicalApp-PHP/blob/fb99ccf29fddb48bcc6ac036b8bc9a9fa1c5b1fc/app/services/DatabaseConnection.php#L10-L17
Datele de configurare/credentialele se stocheaza intotdeauna intr-un fisier separat si nicidecum intr-un bloc de cod. Daca un programator va lucra pe codul tau si va trebui sa schimbe credentialele pentru toate serviciile (presupunem ca ai mai multe: mysql, redis, queue service, mail service, etc), ce va face? Va face munca de cercetare in cod pentru a gasi unde sunt setate fiecare dintre ele?

**Comment by BiancaBM** [comment]
Voi extrage ca si constante intr-un fisier de config
