### ISSUE TITLE
HTML dublificat pt ca nu se foloseste nicio solutie de template

### ISSUE THREAD

**Issue by sica07** [BiancaBM/medicalApp-PHP#5]
https://github.com/BiancaBM/medicalApp-PHP/blob/fb99ccf29fddb48bcc6ac036b8bc9a9fa1c5b1fc/app/views/loginpage.phtml#L1-L10
Nu folosesti nicio solutie de templating (php-ul in sine este un template engine) si de aceea in fiecare pagina html trebuie sa re-scrii aceleasi linii de cod (in header de exemplu unde incarci css-ul si html-ul).
In proiect folosim twig-ul ca template engine. 
Deasemenea, in task-urile pt laborator am creat o clasa de baza Controller (in interiorul framework-ului) care se ocupa de management-ul template-urilor.

**Comment by BiancaBM** [comment]
Rezolvat. Am folosit twig
