### ISSUE TITLE
Nu se trateaza situatia rutelor dinamice

### ISSUE THREAD

**Issue by sica07** [BiancaBM/medicalApp-PHP#6]
https://github.com/BiancaBM/medicalApp-PHP/blob/fb99ccf29fddb48bcc6ac036b8bc9a9fa1c5b1fc/src/Router.php#L7

Nu inteleg cum tratezi situatia rutelor dinamice? Sa zicem ca vreau sa accesez pacientul cu id-ul 73 (patient/73)?

**Comment by BiancaBM** [comment]
Nu am tratat rutele dinamice si am folosit redirectari in caz ca se incearca accesarea unui url din browser si nu printr-un form. Am plecat de la ideea ca nimic sa nu fie shareuibil. De ID as avea nevoie doar la Edit in rest am doar tabele.

**Comment by sica07** [comment]
Pai si cum as putea vedea un pacient anume? Cum il accesez (ca user logat,
care am drept de acces la aceasta informatie)?
Legat de cazul in care "nimic sa nu fie shareuibil", ai foarte mare
dreptate si e o masura obligatorie pentru securitate, DAR  pentru asta se
folosesc guard-uri/middelware/etc. Exista un task special dedicat pentru
asta, cel referitor la guard-uri. Poti sa examinezi solutia in framework-ul
ce ti l-am trimis.

În sâm., 5 ian. 2019 la 19:27, BiancaBM <notifications@github.com> a scris:

**Comment by BiancaBM** [comment]
Nu am dezvoltat pagina de vizualizare pacient. Toate informatile despre un utilizator/pacient sunt disponibile doar in tabel. Voi face ca paginile de edit  sa fie accesibile prin rute dinamice

**Comment by sica07** [comment]
Pai si pagina de editare a pacientului o putem considera (intr-un fel)
pagina de vizualizare :) Sa folosesti cum ai zis, te rog, rute dinamice la
pagina de editare. Asta e solutia folosita de toate frameworkurile
(indiferent de limbaj: .Net, Spring, Django).


În sâm., 5 ian. 2019 la 19:39, BiancaBM <notifications@github.com> a scris:

**Comment by BiancaBM** [comment]
Rezolvat :)
