### ISSUE TITLE
De ce trebuie ca toate url-urile sa se termine cu un slash?

### ISSUE THREAD

**Issue by sica07** [BiancaBM/medicalApp-PHP#7]
https://github.com/BiancaBM/medicalApp-PHP/blob/fb99ccf29fddb48bcc6ac036b8bc9a9fa1c5b1fc/src/Router.php#L13

Nu spun ca e gresit, ci pur si simplu ca nu inteleg motivul.

**Comment by BiancaBM** [comment]
Am ca rute si varianta de "null" si "/".
"/" merge spre un IndexController de unde se face prima redirectare.
